export const colors = {
	// Main Colors
	// Primary
	primaryKey: "#F27A1A",
	primaryHighlight: "#EF6114",
	primaryContrast: "#FEF2E8",
	// Success
	successKey: "#0BC15C",
	successHighlight: "#09A44E",
	successContrast: "#E7F9EF",
	// Danger
	dangerKey: "#FF5043",
	dangerHighlight: "#FF3028",
	dangerContrast: "#FFEEEC",
	// Warning
	warningKey: "#FFB600",
	warningHighlight: "#FF9800",
	warningContrast: "#FFF8E6",
	// Neutral
	neutralNone: "#000000",
	neutralSemi: "#0f0f0f",
	neutralDarkest: "#0F131A",
	neutralDarker: "#273142",
	neutralDark: "#6E7787",
	neutralLight: "#95A1B5",
	neutralLighter: "#AFBBCA",
	neutralLightest: "#F1F2F7",
	neutralFull: "#FFFFFF",
	// Transparent
	transparentHighlight: "#00000010",

	// Will Be Deprecated
	// Color
	white: "#FFFFFF",
	black: "#000000",
	transparent: "transparent",
	primaryColor: "#F27A1A",
	secondaryColor: "#273142",
	tertiaryColor: "#F1F2F7",
	successColor: "#0BC15C",
	dangerColor: "#FF5043",
	warningColor: "#FFB600",
	alternativeColor: "#5794FF",
	featuredColor: "#8C4EFF",
	// Hover
	primaryHover: "#EF6114",
	secondaryHover: "#0F131A",
	tertiaryHover: "#D5D9E1",
	successHover: "#09A44E",
	dangerHover: "#FF3028",
	warningHover: "#FF9800",
	alternativeHover: "#457EFF",
	featuredHover: "#753EFF",
	// Background
	primaryBackground: "#F1F2F7",
	accentBackground: "#FEF2E8",
	secondaryBackground: "#FFFFFF",
	tertiaryBackground: "#F7F7FA",
	successBackground: "#E7F9EF",
	alertBackground: "#FFEEEC",
	warningBackground: "#FFF8E6",
	infoBackground: "#EEF4FF",
	featuredBackground: "#F4EDFF",
	// Border Color
	borderColor: "#D5D9E1",
	// Content
	contentPrimary: "#273142",
	contentSecondary: "#6E7787",
	contentTertiary: "#95A1B5",
	contentPassive: "#AFBBCA",
};
